name: Build and publish

on:
  release:
    types: [published]
    # branches: [main]

# on:
#   workflow_run:
#     workflows: ["Dojo UI Release"]
#     types: [completed]


jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}