name: Build Dojo UI

on:
  push:
    branches:
      - main
      - staging
      - dev
      - junk/github-action-test

jobs:
  ui_build:
    name: Release
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.12.0'
      - name: NPM Install
        run: npm install --force
      - name: Run Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL_DEV }}
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL_STAGING }}
          fi
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            .next
