name: Build UI

on:
  push:
    branches:
      - main
      - staging
      - dev
      - "fix/docker-build"

jobs:
  build_ui:
    name: Build UI
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.npm
          key: dojo-ui-node-modules
          restore-keys: |
            dojo-ui-node-modules

      - name: NPM Install
        run: npm install --force

      - name: Run Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL_DEV }}
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL_STAGING }}
          fi
          npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            .next
  build_image:
    uses: .github/workflows/docker_build.yaml@ref
    needs:
      - build_ui
