on:
  release:
    types:
      - published
  workflow_call:

jobs:
  docker_publish:
    name: Docker Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Branch name
        id: get_branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SANITIZED_BRANCH_NAME=${BRANCH_NAME//\//-}
          echo "BRANCH_NAME=$SANITIZED_BRANCH_NAME" >> $GITHUB_ENV

      - name: Build image with env tag
        if: github.ref == 'refs/heads/dev'
          || github.ref == 'refs/heads/staging'
          || github.ref == 'refs/heads/tensorplex-dev'
          || github.ref == 'refs/heads/tensorplex-staging'
          || github.ref == 'refs/heads/tensorplex-prod'
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ env.BRANCH_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with semver tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}